### ISSUE TITLE
Crash upon receiving a message from a user with no image

### ISSUE THREAD

**Issue by marcomicera** [MadKoko/KokoLab3#12]
The received image is null, hence causing a NullPointerException upon retrieving the sender's profile picture.

**Comment by dgrimaldi** [comment]
Il bug di ieri sera non si è ripetuto stamattina. Quando esco da editProfile salva sempre un immagine

**Comment by marcomicera** [comment]
@dgrimaldi è stato cambiato qualcosa nel frattempo?

**Comment by dgrimaldi** [comment]
no, ho sistemato la ui di editProfile

**Comment by marcomicera** [comment]
@dgrimaldi hai creato un nuovo utente (senza immagine) per ricreare questo bug?

**Comment by dgrimaldi** [comment]
Sia quando creo un nuovo utente sia quando ne modifico uno. Salva sempre un'immagine
